import type { TenderReviewMockData } from './types'

export const tenderReviewMockData: TenderReviewMockData = {
  projectInfo: {
    name: '滨江新区市政道路改造工程 EPC 总承包',
    code: 'BJ-2026-ZB-018',
    method: '综合评估法',
    controlPrice: '¥ 1.35 亿元',
    reviewDate: '2026 年 6 月 18 日',
    reportNo: 'TR-2026-0618-018',
  },
  projects: [
    {
      id: 'bj-2026-zb-018',
      name: '滨江新区市政道路改造工程 EPC 总承包',
      code: 'BJ-2026-ZB-018',
      method: '综合评估法',
      bidderCount: 4,
      score: '94.5',
      date: '2026-06-18',
      status: 'review',
      stage: '评分完成 · 待复核',
      progress: 100,
      riskCount: 2,
      recommendedBidder: '丙建设集团有限公司',
    },
    {
      id: 'bj-2026-zb-014',
      name: '城东污水处理厂提标改造工程',
      code: 'BJ-2026-ZB-014',
      method: '综合评估法',
      bidderCount: 3,
      score: '-',
      date: '2026-06-15',
      status: 'doing',
      stage: '资格审查中',
      progress: 42,
      riskCount: 1,
      recommendedBidder: '分析中',
    },
    {
      id: 'bj-2026-zb-011',
      name: '第三实验小学迁建项目（施工）',
      code: 'BJ-2026-ZB-011',
      method: '经评审最低价',
      bidderCount: 5,
      score: '-',
      date: '2026-06-12',
      status: 'doing',
      stage: '评分要点提取中',
      progress: 68,
      riskCount: 0,
      recommendedBidder: '分析中',
    },
    {
      id: 'bj-2026-zb-009',
      name: '城市轨道交通 4 号线机电安装',
      code: 'BJ-2026-ZB-009',
      method: '综合评估法',
      bidderCount: 6,
      score: '96.2',
      date: '2026-06-05',
      status: 'done',
      stage: '已完成',
      progress: 100,
      riskCount: 0,
      recommendedBidder: '丁工程集团有限公司',
    },
    {
      id: 'bj-2026-zb-006',
      name: '人民医院住院综合楼装饰工程',
      code: 'BJ-2026-ZB-006',
      method: '综合评估法',
      bidderCount: 4,
      score: '89.7',
      date: '2026-05-28',
      status: 'done',
      stage: '已完成',
      progress: 100,
      riskCount: 3,
      recommendedBidder: '省建工集团股份有限公司',
    },
    {
      id: 'bj-2026-zb-003',
      name: '高新区智慧路灯采购及安装',
      code: 'BJ-2026-ZB-003',
      method: '经评审最低价',
      bidderCount: 7,
      score: '91.0',
      date: '2026-05-20',
      status: 'done',
      stage: '已完成',
      progress: 100,
      riskCount: 1,
      recommendedBidder: '市政建设集团有限公司',
    },
  ],
  tenderFiles: [
    { name: '滨江路改造_招标文件_终版.pdf', size: 8650752 },
    { name: '资格预审及评分办法_附件.docx', size: 1258291 },
  ],
  uploadBidders: [
    {
      id: 1,
      name: '丙建设集团有限公司',
      files: [
        { name: '投标文件_正本.pdf', size: 15728640 },
        { name: '商务标_报价文件.pdf', size: 4194304 },
        { name: '技术标_施工组织设计.pdf', size: 9437184 },
        { name: '资质及类似业绩证明.pdf', size: 6291456 },
      ],
    },
    {
      id: 2,
      name: '丁工程集团有限公司',
      files: [
        { name: '投标文件_正本.pdf', size: 14680064 },
        { name: '商务标_报价文件.pdf', size: 3984588 },
        { name: '技术标.pdf', size: 8388608 },
      ],
    },
    {
      id: 3,
      name: '省建工集团股份有限公司',
      files: [
        { name: '投标文件_正本.pdf', size: 12582912 },
        { name: '商务及技术标.pdf', size: 7340032 },
      ],
    },
    {
      id: 4,
      name: '市政建设集团有限公司',
      files: [{ name: '投标文件_正本.pdf', size: 11534336 }],
    },
  ],
  reviewBidders: [
    {
      id: 'A',
      tag: '甲',
      name: '丙建设集团有限公司',
      short: '丙建集团',
      total: 94.5,
      rank: 1,
    },
    {
      id: 'B',
      tag: '乙',
      name: '丁工程集团有限公司',
      short: '丁工集团',
      total: 91.5,
      rank: 2,
    },
    {
      id: 'C',
      tag: '丙',
      name: '省建工集团股份有限公司',
      short: '省建工',
      total: 88,
      rank: 3,
    },
    {
      id: 'D',
      tag: '丁',
      name: '市政建设集团有限公司',
      short: '市政集团',
      total: 83,
      rank: 4,
    },
  ],
  categories: [
    {
      key: 'qual',
      label: '资格审查',
      items: [
        {
          id: 'q1',
          title: '独立法人资格',
          desc: '投标人须为依法注册的独立企业法人，营业执照在有效期内。',
          status: 'pass',
          loc: 0,
          aiNote:
            '营业执照载明独立法人，统一社会信用代码 9111...56XK，状态存续。',
        },
        {
          id: 'q2',
          title: '建筑工程施工总承包特级资质',
          desc: '须具备住建部颁发的施工总承包特级资质（招标要求甲级及以上）。',
          status: 'pass',
          loc: 1,
          aiNote: '持特级资质证书 A123456789，等级高于招标最低要求。',
        },
        {
          id: 'q3',
          title: '安全生产许可证有效',
          desc: '安全生产许可证须在有效期内且未被暂扣吊销。',
          status: 'pass',
          loc: 2,
          aiNote: '安许证编号（建）JZ安许证字...，有效期至 2027-09，正常。',
        },
        {
          id: 'q4',
          title: '近三年无重大安全事故',
          desc: '投标人近三年内未发生较大及以上等级安全生产事故。',
          status: 'warning',
          loc: 3,
          aiNote: '投标文件为自述承诺，未附主管部门证明，建议人工核验原件。',
        },
        {
          id: 'q5',
          title: '注册资本 ≥ 5000 万元',
          desc: '注册资本金不低于人民币 5000 万元。',
          status: 'pass',
          loc: 4,
          aiNote: '注册资本 8000 万元，净资产 1.2 亿元，满足且有余量。',
        },
        {
          id: 'q6',
          title: '无失信被执行人记录',
          desc: '未被列入失信被执行人、重大税收违法等名单。',
          status: 'pass',
          loc: 5,
          aiNote: '信用中国 + 中国执行信息公开网核验：无失信、无重大违法记录。',
        },
        {
          id: 'q7',
          title: '近三年财务状况良好',
          desc: '近三年经审计财务报告，连续盈利、无资不抵债。',
          status: 'pass',
          loc: 6,
          aiNote: '2023-2025 审计报告均盈利，资产负债率 52%，处于健康区间。',
        },
      ],
    },
    {
      key: 'tech',
      label: '技术评分',
      items: [
        {
          id: 't1',
          title: '施工组织设计',
          desc: '方案先进性、工艺合理性、重难点应对与资源配置。',
          got: 13.5,
          max: 15,
          loc: 7,
          aiNote: '采用 BIM+智慧工地，工序模拟完整，专家评分均值 13.5/15。',
        },
        {
          id: 't2',
          title: '项目管理团队配置',
          desc: '项目经理、总工及关键岗位人员资历与到岗承诺。',
          got: 9,
          max: 10,
          loc: 8,
          aiNote: '核心团队 15 人，含一级建造师 8 名，岗位匹配度高。',
        },
        {
          id: 't3',
          title: '质量保证措施',
          desc: '质量管理体系、检验制度与一次验收合格率承诺。',
          got: 7.5,
          max: 8,
          loc: 9,
          aiNote: 'ISO9001 认证，三检制+样板引路，承诺合格率 100%。',
        },
        {
          id: 't4',
          title: '安全文明施工措施',
          desc: '安全管理体系、扬尘噪声控制与绿色施工措施。',
          got: 6.5,
          max: 7,
          loc: 10,
          aiNote: '方案完整，绿色施工承诺达标，扣分项为应急演练频次偏低。',
        },
      ],
    },
    {
      key: 'comm',
      label: '商务·信誉',
      items: [
        {
          id: 'c1',
          title: '投标报价',
          desc: '报价合理性与竞争力，对照招标控制价偏离评分。',
          got: 38,
          max: 40,
          loc: 11,
          aiNote: '报价 1.28 亿，较控制价低 5.2%，处合理低价区间。',
        },
        {
          id: 'c2',
          title: '工期承诺',
          desc: '工期合理性与进度保障措施。',
          got: 5,
          max: 5,
          loc: 12,
          aiNote: '承诺 420 日历天，较要求提前 30 天且有进度计划支撑，满分。',
        },
        {
          id: 'c3',
          title: '财务状况',
          desc: '净资产、流动比率等财务健康度。',
          got: 5,
          max: 5,
          loc: 13,
          aiNote: '净资产 1.2 亿、流动比率 1.8，财务指标全部达标。',
        },
        {
          id: 'c4',
          title: '类似项目业绩',
          desc: '近三年同类市政/超高层项目数量与规模。',
          got: 6,
          max: 6,
          loc: 14,
          aiNote: '近三年同类项目 12 个，累计建面 200 万平方米，业绩充分。',
        },
        {
          id: 'c5',
          title: '企业信誉',
          desc: '获奖、信用评级与履约评价。',
          got: 4,
          max: 4,
          loc: 5,
          aiNote: 'AAA 信用评级，省级安全先进单位 3 次，无不良履约记录。',
        },
      ],
    },
  ],
  paragraphs: [
    {
      loc: 0,
      label: '法人资格',
      text: '本公司成立于 2005 年，系经核准登记的独立法人企业，注册资本金 8000 万元，统一社会信用代码 9111000071092156XK。',
    },
    {
      loc: 1,
      label: '资质证书',
      text: '持有住房和城乡建设部颁发的建筑工程施工总承包特级资质（证书编号 A123456789），具备承担本项目的资质条件。',
    },
    {
      loc: 2,
      label: '安全生产许可',
      text: '公司持有有效的安全生产许可证（编号（建）JZ 安许证字...），有效期至 2027 年 9 月，期间未被暂扣或吊销。',
    },
    {
      loc: 3,
      label: '安全事故记录',
      text: '本公司近三年内未发生重大安全生产事故，安全生产记录良好（注：本节为投标人承诺，未随附主管部门出具的证明文件）。',
    },
    {
      loc: 4,
      label: '注册资本',
      text: '公司注册资本金为 8000 万元人民币，净资产达 1.2 亿元，满足招标文件关于注册资本不低于 5000 万元的要求。',
    },
    {
      loc: 5,
      label: '信用记录',
      text: '经信用中国及中国执行信息公开网查询，本公司无失信被执行人记录、无重大税收违法记录，企业信用评级为 AAA 级。',
    },
    {
      loc: 6,
      label: '财务状况',
      text: '近三年经审计财务报告显示公司连续盈利，资产负债率 52%，流动比率 1.8，财务状况稳健，无资不抵债情形。',
    },
    {
      loc: 7,
      label: '施工组织设计',
      text: '本次投标采用 BIM + 智慧工地管理技术，对全部关键工序进行模拟优化，针对软基处理、管线迁改等重难点制定专项方案。',
    },
    {
      loc: 8,
      label: '项目团队',
      text: '拟派项目团队由 15 名核心成员组成，含高级工程师 5 名、一级注册建造师 8 名、专职安全工程师 2 名，均承诺到岗履职。',
    },
    {
      loc: 9,
      label: '质量保证',
      text: '质量管理体系通过 ISO9001 认证，严格执行三检制、样板引路、实测实量等措施，承诺工程一次验收合格率 100%。',
    },
    {
      loc: 10,
      label: '安全文明',
      text: '建立安全生产责任制，落实扬尘与噪声控制、绿色施工措施；应急演练按季度组织，覆盖主要风险源。',
    },
    {
      loc: 11,
      label: '投标报价',
      text: '投标总报价为人民币 1.28 亿元，较招标控制价下浮 5.2%，综合单价合理，报价构成清晰完整，无不平衡报价。',
    },
    {
      loc: 12,
      label: '工期承诺',
      text: '承诺总工期 420 个日历天，较招标文件要求的 450 天提前 30 天，并制定了分阶段进度计划与保障措施。',
    },
    {
      loc: 13,
      label: '财务报表',
      text: '附 2023-2025 年度审计报告：营业收入与净利润逐年增长，净资产 1.2 亿元，流动比率 1.8，偿债能力良好。',
    },
    {
      loc: 14,
      label: '类似业绩',
      text: '近三年完成同类市政与超高层项目 12 项，其中市政道路 7 项、综合管廊 2 项，累计建筑面积超 200 万平方米。',
    },
  ],
  compareGroups: [
    {
      name: '商务标',
      rows: [
        { name: '投标报价', max: 40, cells: [38, 40, 36, 37] },
        { name: '工期承诺', max: 5, cells: [5, 4.5, 5, 4] },
        { name: '财务状况', max: 5, cells: [5, 4.5, 4, 4.5] },
      ],
    },
    {
      name: '技术标',
      rows: [
        { name: '施工组织设计', max: 15, cells: [13.5, 12, 13, 11] },
        { name: '项目管理团队', max: 10, cells: [9, 8.5, 8, 7.5] },
        { name: '质量保证措施', max: 8, cells: [7.5, 7, 6.5, 6] },
        { name: '安全文明施工', max: 7, cells: [6.5, 6, 6.5, 5.5] },
      ],
    },
    {
      name: '信誉业绩',
      rows: [
        { name: '类似项目业绩', max: 6, cells: [6, 5.5, 5, 4.5] },
        { name: '企业信誉', max: 4, cells: [4, 3.5, 4, 3] },
      ],
    },
  ],
}
