// Generated by scripts/generate_document_formats.py. Do not edit by hand.
export const SUPPORTED_DOCUMENT_FORMATS_VERSION = 1 as const

export const SUPPORTED_DOCUMENT_FORMAT_GROUPS = {
  text: ['.txt', '.csv', '.md', '.json', '.tsv'],
  images: ['.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp', '.webp'],
  word_native: ['.docx'],
  word_legacy: ['.doc'],
  excel_ooxml: ['.xlsx', '.xlsm'],
  excel_xls: ['.xls'],
  excel_xlsb: ['.xlsb'],
  presentation_native: ['.pptx'],
  office_convert: ['.ppt', '.odt', '.ods', '.odp'],
  pdf: ['.pdf'],
} as const

export const SUPPORTED_DOCUMENT_EXTENSIONS = Object.values(
  SUPPORTED_DOCUMENT_FORMAT_GROUPS
).flat()

export const ACCEPTED_DOCUMENT_FILE_TYPES =
  SUPPORTED_DOCUMENT_EXTENSIONS.join(',')
