model_list:
  - model_name: claude-opus-4-8
    litellm_params:
      model: openai/qwen3.6
      api_base: http://2.87.85.67:8100/v1
      api_key: sk-hATxkq_E1y7wNmtXtDYCdMZXgpeaFf5Kabc7567765767667

  - model_name: "*"
    litellm_params:
      model: openai/qwen3.6
      api_base: http://2.87.85.67:8100/v1
      api_key: sk-hATxkq_E1y7wNmtXtDYCdMZXgpeaFf5Kabc67567567

litellm_settings:
  drop_params: true
  num_retries: 2
