/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedOcrRouteImport } from './routes/_authenticated/ocr'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedContractsTenderReviewRouteImport } from './routes/_authenticated/contracts/tender-review'
import { Route as AuthenticatedAuditSubmitRouteImport } from './routes/_authenticated/audit/submit'
import { Route as AuthenticatedSectionPageRouteImport } from './routes/_authenticated/$section/$page'
import { Route as AuthenticatedContractsTenderReviewIndexRouteImport } from './routes/_authenticated/contracts/tender-review/index'
import { Route as AuthenticatedContractsTenderReviewHistoryRouteImport } from './routes/_authenticated/contracts/tender-review/history'
import { Route as AuthenticatedAuditTasksTaskIdRouteImport } from './routes/_authenticated/audit/tasks/$taskId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOcrRoute = AuthenticatedOcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAuditRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsTenderReviewRoute =
  AuthenticatedContractsTenderReviewRouteImport.update({
    id: '/tender-review',
    path: '/tender-review',
    getParentRoute: () => AuthenticatedContractsRoute,
  } as any)
const AuthenticatedAuditSubmitRoute =
  AuthenticatedAuditSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => AuthenticatedAuditRoute,
  } as any)
const AuthenticatedSectionPageRoute =
  AuthenticatedSectionPageRouteImport.update({
    id: '/$section/$page',
    path: '/$section/$page',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsTenderReviewIndexRoute =
  AuthenticatedContractsTenderReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedContractsTenderReviewRoute,
  } as any)
const AuthenticatedContractsTenderReviewHistoryRoute =
  AuthenticatedContractsTenderReviewHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedContractsTenderReviewRoute,
  } as any)
const AuthenticatedAuditTasksTaskIdRoute =
  AuthenticatedAuditTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedAuditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/ocr': typeof AuthenticatedOcrRoute
  '/$section/$page': typeof AuthenticatedSectionPageRoute
  '/audit/submit': typeof AuthenticatedAuditSubmitRoute
  '/contracts/tender-review': typeof AuthenticatedContractsTenderReviewRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/audit/tasks/$taskId': typeof AuthenticatedAuditTasksTaskIdRoute
  '/contracts/tender-review/history': typeof AuthenticatedContractsTenderReviewHistoryRoute
  '/contracts/tender-review/': typeof AuthenticatedContractsTenderReviewIndexRoute
}
export interface FileRoutesByTo {
  '/otp': typeof authOtpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ocr': typeof AuthenticatedOcrRoute
  '/': typeof AuthenticatedIndexRoute
  '/$section/$page': typeof AuthenticatedSectionPageRoute
  '/audit/submit': typeof AuthenticatedAuditSubmitRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/audit/tasks/$taskId': typeof AuthenticatedAuditTasksTaskIdRoute
  '/contracts/tender-review/history': typeof AuthenticatedContractsTenderReviewHistoryRoute
  '/contracts/tender-review': typeof AuthenticatedContractsTenderReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/audit': typeof AuthenticatedAuditRouteWithChildren
  '/_authenticated/contracts': typeof AuthenticatedContractsRouteWithChildren
  '/_authenticated/ocr': typeof AuthenticatedOcrRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$section/$page': typeof AuthenticatedSectionPageRoute
  '/_authenticated/audit/submit': typeof AuthenticatedAuditSubmitRoute
  '/_authenticated/contracts/tender-review': typeof AuthenticatedContractsTenderReviewRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/audit/tasks/$taskId': typeof AuthenticatedAuditTasksTaskIdRoute
  '/_authenticated/contracts/tender-review/history': typeof AuthenticatedContractsTenderReviewHistoryRoute
  '/_authenticated/contracts/tender-review/': typeof AuthenticatedContractsTenderReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/otp'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/audit'
    | '/contracts'
    | '/ocr'
    | '/$section/$page'
    | '/audit/submit'
    | '/contracts/tender-review'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/audit/'
    | '/contracts/'
    | '/settings/'
    | '/audit/tasks/$taskId'
    | '/contracts/tender-review/history'
    | '/contracts/tender-review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/otp'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ocr'
    | '/'
    | '/$section/$page'
    | '/audit/submit'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/audit'
    | '/contracts'
    | '/settings'
    | '/audit/tasks/$taskId'
    | '/contracts/tender-review/history'
    | '/contracts/tender-review'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/otp'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/audit'
    | '/_authenticated/contracts'
    | '/_authenticated/ocr'
    | '/_authenticated/'
    | '/_authenticated/$section/$page'
    | '/_authenticated/audit/submit'
    | '/_authenticated/contracts/tender-review'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/audit/'
    | '/_authenticated/contracts/'
    | '/_authenticated/settings/'
    | '/_authenticated/audit/tasks/$taskId'
    | '/_authenticated/contracts/tender-review/history'
    | '/_authenticated/contracts/tender-review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocr': {
      id: '/_authenticated/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof AuthenticatedOcrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/tender-review': {
      id: '/_authenticated/contracts/tender-review'
      path: '/tender-review'
      fullPath: '/contracts/tender-review'
      preLoaderRoute: typeof AuthenticatedContractsTenderReviewRouteImport
      parentRoute: typeof AuthenticatedContractsRoute
    }
    '/_authenticated/audit/submit': {
      id: '/_authenticated/audit/submit'
      path: '/submit'
      fullPath: '/audit/submit'
      preLoaderRoute: typeof AuthenticatedAuditSubmitRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
    '/_authenticated/$section/$page': {
      id: '/_authenticated/$section/$page'
      path: '/$section/$page'
      fullPath: '/$section/$page'
      preLoaderRoute: typeof AuthenticatedSectionPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/tender-review/': {
      id: '/_authenticated/contracts/tender-review/'
      path: '/'
      fullPath: '/contracts/tender-review/'
      preLoaderRoute: typeof AuthenticatedContractsTenderReviewIndexRouteImport
      parentRoute: typeof AuthenticatedContractsTenderReviewRoute
    }
    '/_authenticated/contracts/tender-review/history': {
      id: '/_authenticated/contracts/tender-review/history'
      path: '/history'
      fullPath: '/contracts/tender-review/history'
      preLoaderRoute: typeof AuthenticatedContractsTenderReviewHistoryRouteImport
      parentRoute: typeof AuthenticatedContractsTenderReviewRoute
    }
    '/_authenticated/audit/tasks/$taskId': {
      id: '/_authenticated/audit/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/audit/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedAuditTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAuditRouteChildren {
  AuthenticatedAuditSubmitRoute: typeof AuthenticatedAuditSubmitRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedAuditTasksTaskIdRoute: typeof AuthenticatedAuditTasksTaskIdRoute
}

const AuthenticatedAuditRouteChildren: AuthenticatedAuditRouteChildren = {
  AuthenticatedAuditSubmitRoute: AuthenticatedAuditSubmitRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedAuditTasksTaskIdRoute: AuthenticatedAuditTasksTaskIdRoute,
}

const AuthenticatedAuditRouteWithChildren =
  AuthenticatedAuditRoute._addFileChildren(AuthenticatedAuditRouteChildren)

interface AuthenticatedContractsTenderReviewRouteChildren {
  AuthenticatedContractsTenderReviewHistoryRoute: typeof AuthenticatedContractsTenderReviewHistoryRoute
  AuthenticatedContractsTenderReviewIndexRoute: typeof AuthenticatedContractsTenderReviewIndexRoute
}

const AuthenticatedContractsTenderReviewRouteChildren: AuthenticatedContractsTenderReviewRouteChildren =
  {
    AuthenticatedContractsTenderReviewHistoryRoute:
      AuthenticatedContractsTenderReviewHistoryRoute,
    AuthenticatedContractsTenderReviewIndexRoute:
      AuthenticatedContractsTenderReviewIndexRoute,
  }

const AuthenticatedContractsTenderReviewRouteWithChildren =
  AuthenticatedContractsTenderReviewRoute._addFileChildren(
    AuthenticatedContractsTenderReviewRouteChildren,
  )

interface AuthenticatedContractsRouteChildren {
  AuthenticatedContractsTenderReviewRoute: typeof AuthenticatedContractsTenderReviewRouteWithChildren
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
}

const AuthenticatedContractsRouteChildren: AuthenticatedContractsRouteChildren =
  {
    AuthenticatedContractsTenderReviewRoute:
      AuthenticatedContractsTenderReviewRouteWithChildren,
    AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  }

const AuthenticatedContractsRouteWithChildren =
  AuthenticatedContractsRoute._addFileChildren(
    AuthenticatedContractsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRouteWithChildren
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRouteWithChildren
  AuthenticatedOcrRoute: typeof AuthenticatedOcrRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSectionPageRoute: typeof AuthenticatedSectionPageRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAuditRoute: AuthenticatedAuditRouteWithChildren,
  AuthenticatedContractsRoute: AuthenticatedContractsRouteWithChildren,
  AuthenticatedOcrRoute: AuthenticatedOcrRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSectionPageRoute: AuthenticatedSectionPageRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
