#!/usr/bin/env python3
"""Generate the frontend document-format contract from the canonical manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = PROJECT_ROOT / "shared" / "supported-document-formats.json"
OUTPUT_PATH = (
    PROJECT_ROOT
    / "agent-front"
    / "src"
    / "features"
    / "contract"
    / "tender-review"
    / "supported-document-formats.ts"
)
GROUP_KEYS = (
    "text",
    "images",
    "word_native",
    "word_legacy",
    "excel_ooxml",
    "excel_xls",
    "excel_xlsb",
    "presentation_native",
    "office_convert",
    "pdf",
)


def load_manifest() -> dict[str, Any]:
    """Load and validate the canonical format manifest."""
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    if manifest.get("version") != 1:
        raise ValueError("supported document format manifest version must be 1")
    groups = manifest.get("groups")
    if not isinstance(groups, dict) or tuple(groups) != GROUP_KEYS:
        raise ValueError(f"format groups must be ordered exactly as {GROUP_KEYS}")

    extensions: list[str] = []
    for group_name, suffixes in groups.items():
        if not isinstance(suffixes, list) or not suffixes:
            raise ValueError(f"format group {group_name!r} must be a non-empty array")
        for suffix in suffixes:
            if (
                not isinstance(suffix, str)
                or not suffix.startswith(".")
                or suffix != suffix.lower()
            ):
                raise ValueError(f"invalid document suffix: {suffix!r}")
            extensions.append(suffix)
    if len(extensions) != len(set(extensions)):
        raise ValueError("document suffixes must be unique across groups")
    if ".heic" in extensions:
        raise ValueError("HEIC is not supported by the runtime image")
    return manifest


def render_typescript(manifest: dict[str, Any]) -> str:
    """Render deterministic TypeScript constants from a validated manifest."""
    groups = manifest["groups"]
    lines = [
        "// Generated by scripts/generate_document_formats.py. Do not edit by hand.",
        f"export const SUPPORTED_DOCUMENT_FORMATS_VERSION = {manifest['version']} as const",
        "",
        "export const SUPPORTED_DOCUMENT_FORMAT_GROUPS = {",
    ]
    for group_name, suffixes in groups.items():
        rendered_suffixes = ", ".join(repr(suffix) for suffix in suffixes)
        lines.append(f"  {group_name}: [{rendered_suffixes}],")
    lines.extend(
        [
            "} as const",
            "",
            "export const SUPPORTED_DOCUMENT_EXTENSIONS = Object.values(",
            "  SUPPORTED_DOCUMENT_FORMAT_GROUPS",
            ").flat()",
            "",
            "export const ACCEPTED_DOCUMENT_FILE_TYPES =",
            "  SUPPORTED_DOCUMENT_EXTENSIONS.join(',')",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    """Generate or verify the committed frontend document-format contract."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed TypeScript output differs from the manifest",
    )
    args = parser.parse_args()

    try:
        expected = render_typescript(load_manifest())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"format generation failed: {error}", file=sys.stderr)
        return 2

    if args.check:
        actual = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if actual != expected:
            print(
                "generated document formats are stale; run scripts/generate_document_formats.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
